// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Total         int32                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	StartSaleAt   string                 `protobuf:"bytes,7,opt,name=start_sale_at,json=startSaleAt,proto3" json:"start_sale_at,omitempty"`
	EndSaleAt     string                 `protobuf:"bytes,8,opt,name=end_sale_at,json=endSaleAt,proto3" json:"end_sale_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketClass) Reset() {
	*x = TicketClass{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketClass) ProtoMessage() {}

func (x *TicketClass) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketClass.ProtoReflect.Descriptor instead.
func (*TicketClass) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *TicketClass) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketClass) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TicketClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketClass) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *TicketClass) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TicketClass) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TicketClass) GetStartSaleAt() string {
	if x != nil {
		return x.StartSaleAt
	}
	return ""
}

func (x *TicketClass) GetEndSaleAt() string {
	if x != nil {
		return x.EndSaleAt
	}
	return ""
}

func (x *TicketClass) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TicketClass) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateTicketClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int64                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	StartSaleAt   string                 `protobuf:"bytes,6,opt,name=start_sale_at,json=startSaleAt,proto3" json:"start_sale_at,omitempty"`
	EndSaleAt     string                 `protobuf:"bytes,7,opt,name=end_sale_at,json=endSaleAt,proto3" json:"end_sale_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketClassRequest) Reset() {
	*x = CreateTicketClassRequest{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketClassRequest) ProtoMessage() {}

func (x *CreateTicketClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketClassRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketClassRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicketClassRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateTicketClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicketClassRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *CreateTicketClassRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTicketClassRequest) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CreateTicketClassRequest) GetStartSaleAt() string {
	if x != nil {
		return x.StartSaleAt
	}
	return ""
}

func (x *CreateTicketClassRequest) GetEndSaleAt() string {
	if x != nil {
		return x.EndSaleAt
	}
	return ""
}

type CreateTicketClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketClass   *TicketClass           `protobuf:"bytes,1,opt,name=ticket_class,json=ticketClass,proto3" json:"ticket_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketClassResponse) Reset() {
	*x = CreateTicketClassResponse{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketClassResponse) ProtoMessage() {}

func (x *CreateTicketClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketClassResponse.ProtoReflect.Descriptor instead.
func (*CreateTicketClassResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTicketClassResponse) GetTicketClass() *TicketClass {
	if x != nil {
		return x.TicketClass
	}
	return nil
}

type UpdateTicketClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int64                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	StartSaleAt   string                 `protobuf:"bytes,6,opt,name=start_sale_at,json=startSaleAt,proto3" json:"start_sale_at,omitempty"`
	EndSaleAt     string                 `protobuf:"bytes,7,opt,name=end_sale_at,json=endSaleAt,proto3" json:"end_sale_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketClassRequest) Reset() {
	*x = UpdateTicketClassRequest{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketClassRequest) ProtoMessage() {}

func (x *UpdateTicketClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketClassRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketClassRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTicketClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTicketClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTicketClassRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *UpdateTicketClassRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateTicketClassRequest) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UpdateTicketClassRequest) GetStartSaleAt() string {
	if x != nil {
		return x.StartSaleAt
	}
	return ""
}

func (x *UpdateTicketClassRequest) GetEndSaleAt() string {
	if x != nil {
		return x.EndSaleAt
	}
	return ""
}

type UpdateTicketClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketClass   *TicketClass           `protobuf:"bytes,1,opt,name=ticket_class,json=ticketClass,proto3" json:"ticket_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketClassResponse) Reset() {
	*x = UpdateTicketClassResponse{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketClassResponse) ProtoMessage() {}

func (x *UpdateTicketClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketClassResponse.ProtoReflect.Descriptor instead.
func (*UpdateTicketClassResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTicketClassResponse) GetTicketClass() *TicketClass {
	if x != nil {
		return x.TicketClass
	}
	return nil
}

type FindOneTicketClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOneTicketClassRequest) Reset() {
	*x = FindOneTicketClassRequest{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOneTicketClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneTicketClassRequest) ProtoMessage() {}

func (x *FindOneTicketClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneTicketClassRequest.ProtoReflect.Descriptor instead.
func (*FindOneTicketClassRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *FindOneTicketClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindOneTicketClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketClass   *TicketClass           `protobuf:"bytes,1,opt,name=ticket_class,json=ticketClass,proto3" json:"ticket_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOneTicketClassResponse) Reset() {
	*x = FindOneTicketClassResponse{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOneTicketClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneTicketClassResponse) ProtoMessage() {}

func (x *FindOneTicketClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneTicketClassResponse.ProtoReflect.Descriptor instead.
func (*FindOneTicketClassResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *FindOneTicketClassResponse) GetTicketClass() *TicketClass {
	if x != nil {
		return x.TicketClass
	}
	return nil
}

type FindManyTicketClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindManyTicketClassRequest) Reset() {
	*x = FindManyTicketClassRequest{}
	mi := &file_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindManyTicketClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindManyTicketClassRequest) ProtoMessage() {}

func (x *FindManyTicketClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindManyTicketClassRequest.ProtoReflect.Descriptor instead.
func (*FindManyTicketClassRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *FindManyTicketClassRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FindManyTicketClassRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindManyTicketClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketClasses []*TicketClass         `protobuf:"bytes,1,rep,name=ticket_classes,json=ticketClasses,proto3" json:"ticket_classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindManyTicketClassResponse) Reset() {
	*x = FindManyTicketClassResponse{}
	mi := &file_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindManyTicketClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindManyTicketClassResponse) ProtoMessage() {}

func (x *FindManyTicketClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindManyTicketClassResponse.ProtoReflect.Descriptor instead.
func (*FindManyTicketClassResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *FindManyTicketClassResponse) GetTicketClasses() []*TicketClass {
	if x != nil {
		return x.TicketClasses
	}
	return nil
}

type DeleteTicketClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketClassRequest) Reset() {
	*x = DeleteTicketClassRequest{}
	mi := &file_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketClassRequest) ProtoMessage() {}

func (x *DeleteTicketClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketClassRequest.ProtoReflect.Descriptor instead.
func (*DeleteTicketClassRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTicketClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReserveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketClassId string                 `protobuf:"bytes,1,opt,name=ticket_class_id,json=ticketClassId,proto3" json:"ticket_class_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItem) Reset() {
	*x = ReserveItem{}
	mi := &file_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItem) ProtoMessage() {}

func (x *ReserveItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItem.ProtoReflect.Descriptor instead.
func (*ReserveItem) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ReserveItem) GetTicketClassId() string {
	if x != nil {
		return x.TicketClassId
	}
	return ""
}

func (x *ReserveItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCode     string                 `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	Items         []*ReserveItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ReserveRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *ReserveRequest) GetItems() []*ReserveItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCode     string                 `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCode     string                 `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

type GetAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketClassId string                 `protobuf:"bytes,1,opt,name=ticket_class_id,json=ticketClassId,proto3" json:"ticket_class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailabilityRequest) Reset() {
	*x = GetAvailabilityRequest{}
	mi := &file_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRequest) ProtoMessage() {}

func (x *GetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *GetAvailabilityRequest) GetTicketClassId() string {
	if x != nil {
		return x.TicketClassId
	}
	return ""
}

type GetAvailabilityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AvailableQuantity int32                  `protobuf:"varint,1,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAvailabilityResponse) Reset() {
	*x = GetAvailabilityResponse{}
	mi := &file_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityResponse) ProtoMessage() {}

func (x *GetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *GetAvailabilityResponse) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

type CheckAvailabilityItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketClassId string                 `protobuf:"bytes,1,opt,name=ticket_class_id,json=ticketClassId,proto3" json:"ticket_class_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityItem) Reset() {
	*x = CheckAvailabilityItem{}
	mi := &file_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityItem) ProtoMessage() {}

func (x *CheckAvailabilityItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityItem.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityItem) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *CheckAvailabilityItem) GetTicketClassId() string {
	if x != nil {
		return x.TicketClassId
	}
	return ""
}

func (x *CheckAvailabilityItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*CheckAvailabilityItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *CheckAvailabilityRequest) GetItems() []*CheckAvailabilityItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{18}
}

func (x *CheckAvailabilityResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\x05event\x1a\x1bgoogle/protobuf/empty.proto\"\xa1\x02\n" +
	"\vTicketClass\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x05R\x05total\x12\"\n" +
	"\rstart_sale_at\x18\a \x01(\tR\vstartSaleAt\x12\x1e\n" +
	"\vend_sale_at\x18\b \x01(\tR\tendSaleAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xe0\x01\n" +
	"\x18CreateTicketClassRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x03R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\x12\"\n" +
	"\rstart_sale_at\x18\x06 \x01(\tR\vstartSaleAt\x12\x1e\n" +
	"\vend_sale_at\x18\a \x01(\tR\tendSaleAt\"R\n" +
	"\x19CreateTicketClassResponse\x125\n" +
	"\fticket_class\x18\x01 \x01(\v2\x12.event.TicketClassR\vticketClass\"\xd5\x01\n" +
	"\x18UpdateTicketClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x03R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\x12\"\n" +
	"\rstart_sale_at\x18\x06 \x01(\tR\vstartSaleAt\x12\x1e\n" +
	"\vend_sale_at\x18\a \x01(\tR\tendSaleAt\"R\n" +
	"\x19UpdateTicketClassResponse\x125\n" +
	"\fticket_class\x18\x01 \x01(\v2\x12.event.TicketClassR\vticketClass\"+\n" +
	"\x19FindOneTicketClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x1aFindOneTicketClassResponse\x125\n" +
	"\fticket_class\x18\x01 \x01(\v2\x12.event.TicketClassR\vticketClass\"I\n" +
	"\x1aFindManyTicketClassRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"X\n" +
	"\x1bFindManyTicketClassResponse\x129\n" +
	"\x0eticket_classes\x18\x01 \x03(\v2\x12.event.TicketClassR\rticketClasses\"*\n" +
	"\x18DeleteTicketClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\vReserveItem\x12&\n" +
	"\x0fticket_class_id\x18\x01 \x01(\tR\rticketClassId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"x\n" +
	"\x0eReserveRequest\x12\x1d\n" +
	"\n" +
	"order_code\x18\x01 \x01(\tR\torderCode\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.event.ReserveItemR\x05items\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\"/\n" +
	"\x0eConfirmRequest\x12\x1d\n" +
	"\n" +
	"order_code\x18\x01 \x01(\tR\torderCode\"/\n" +
	"\x0eReleaseRequest\x12\x1d\n" +
	"\n" +
	"order_code\x18\x01 \x01(\tR\torderCode\"@\n" +
	"\x16GetAvailabilityRequest\x12&\n" +
	"\x0fticket_class_id\x18\x01 \x01(\tR\rticketClassId\"H\n" +
	"\x17GetAvailabilityResponse\x12-\n" +
	"\x12available_quantity\x18\x01 \x01(\x05R\x11availableQuantity\"[\n" +
	"\x15CheckAvailabilityItem\x12&\n" +
	"\x0fticket_class_id\x18\x01 \x01(\tR\rticketClassId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"N\n" +
	"\x18CheckAvailabilityRequest\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.event.CheckAvailabilityItemR\x05items\"3\n" +
	"\x19CheckAvailabilityResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept2\xa1\x06\n" +
	"\x10InventoryService\x12V\n" +
	"\x11CreateTicketClass\x12\x1f.event.CreateTicketClassRequest\x1a .event.CreateTicketClassResponse\x12V\n" +
	"\x11UpdateTicketClass\x12\x1f.event.UpdateTicketClassRequest\x1a .event.UpdateTicketClassResponse\x12Y\n" +
	"\x12FindOneTicketClass\x12 .event.FindOneTicketClassRequest\x1a!.event.FindOneTicketClassResponse\x12\\\n" +
	"\x13FindManyTicketClass\x12!.event.FindManyTicketClassRequest\x1a\".event.FindManyTicketClassResponse\x12L\n" +
	"\x11DeleteTicketClass\x12\x1f.event.DeleteTicketClassRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x11CheckAvailability\x12\x1f.event.CheckAvailabilityRequest\x1a .event.CheckAvailabilityResponse\x12P\n" +
	"\x0fGetAvailability\x12\x1d.event.GetAvailabilityRequest\x1a\x1e.event.GetAvailabilityResponse\x128\n" +
	"\aReserve\x12\x15.event.ReserveRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\aConfirm\x12\x15.event.ConfirmRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\aRelease\x12\x15.event.ReleaseRequest\x1a\x16.google.protobuf.EmptyB;Z9github.com/vogiaan1904/ticketbottle-proto/proto/inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_inventory_proto_goTypes = []any{
	(*TicketClass)(nil),                 // 0: event.TicketClass
	(*CreateTicketClassRequest)(nil),    // 1: event.CreateTicketClassRequest
	(*CreateTicketClassResponse)(nil),   // 2: event.CreateTicketClassResponse
	(*UpdateTicketClassRequest)(nil),    // 3: event.UpdateTicketClassRequest
	(*UpdateTicketClassResponse)(nil),   // 4: event.UpdateTicketClassResponse
	(*FindOneTicketClassRequest)(nil),   // 5: event.FindOneTicketClassRequest
	(*FindOneTicketClassResponse)(nil),  // 6: event.FindOneTicketClassResponse
	(*FindManyTicketClassRequest)(nil),  // 7: event.FindManyTicketClassRequest
	(*FindManyTicketClassResponse)(nil), // 8: event.FindManyTicketClassResponse
	(*DeleteTicketClassRequest)(nil),    // 9: event.DeleteTicketClassRequest
	(*ReserveItem)(nil),                 // 10: event.ReserveItem
	(*ReserveRequest)(nil),              // 11: event.ReserveRequest
	(*ConfirmRequest)(nil),              // 12: event.ConfirmRequest
	(*ReleaseRequest)(nil),              // 13: event.ReleaseRequest
	(*GetAvailabilityRequest)(nil),      // 14: event.GetAvailabilityRequest
	(*GetAvailabilityResponse)(nil),     // 15: event.GetAvailabilityResponse
	(*CheckAvailabilityItem)(nil),       // 16: event.CheckAvailabilityItem
	(*CheckAvailabilityRequest)(nil),    // 17: event.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil),   // 18: event.CheckAvailabilityResponse
	(*emptypb.Empty)(nil),               // 19: google.protobuf.Empty
}
var file_inventory_proto_depIdxs = []int32{
	0,  // 0: event.CreateTicketClassResponse.ticket_class:type_name -> event.TicketClass
	0,  // 1: event.UpdateTicketClassResponse.ticket_class:type_name -> event.TicketClass
	0,  // 2: event.FindOneTicketClassResponse.ticket_class:type_name -> event.TicketClass
	0,  // 3: event.FindManyTicketClassResponse.ticket_classes:type_name -> event.TicketClass
	10, // 4: event.ReserveRequest.items:type_name -> event.ReserveItem
	16, // 5: event.CheckAvailabilityRequest.items:type_name -> event.CheckAvailabilityItem
	1,  // 6: event.InventoryService.CreateTicketClass:input_type -> event.CreateTicketClassRequest
	3,  // 7: event.InventoryService.UpdateTicketClass:input_type -> event.UpdateTicketClassRequest
	5,  // 8: event.InventoryService.FindOneTicketClass:input_type -> event.FindOneTicketClassRequest
	7,  // 9: event.InventoryService.FindManyTicketClass:input_type -> event.FindManyTicketClassRequest
	9,  // 10: event.InventoryService.DeleteTicketClass:input_type -> event.DeleteTicketClassRequest
	17, // 11: event.InventoryService.CheckAvailability:input_type -> event.CheckAvailabilityRequest
	14, // 12: event.InventoryService.GetAvailability:input_type -> event.GetAvailabilityRequest
	11, // 13: event.InventoryService.Reserve:input_type -> event.ReserveRequest
	12, // 14: event.InventoryService.Confirm:input_type -> event.ConfirmRequest
	13, // 15: event.InventoryService.Release:input_type -> event.ReleaseRequest
	2,  // 16: event.InventoryService.CreateTicketClass:output_type -> event.CreateTicketClassResponse
	4,  // 17: event.InventoryService.UpdateTicketClass:output_type -> event.UpdateTicketClassResponse
	6,  // 18: event.InventoryService.FindOneTicketClass:output_type -> event.FindOneTicketClassResponse
	8,  // 19: event.InventoryService.FindManyTicketClass:output_type -> event.FindManyTicketClassResponse
	19, // 20: event.InventoryService.DeleteTicketClass:output_type -> google.protobuf.Empty
	18, // 21: event.InventoryService.CheckAvailability:output_type -> event.CheckAvailabilityResponse
	15, // 22: event.InventoryService.GetAvailability:output_type -> event.GetAvailabilityResponse
	19, // 23: event.InventoryService.Reserve:output_type -> google.protobuf.Empty
	19, // 24: event.InventoryService.Confirm:output_type -> google.protobuf.Empty
	19, // 25: event.InventoryService.Release:output_type -> google.protobuf.Empty
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
