// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CreatePaymentIntent_FullMethodName           = "/payment.PaymentService/CreatePaymentIntent"
	PaymentService_ConfirmPaymentIntent_FullMethodName          = "/payment.PaymentService/ConfirmPaymentIntent"
	PaymentService_CancelPaymentIntent_FullMethodName           = "/payment.PaymentService/CancelPaymentIntent"
	PaymentService_GetPaymentUrlByIdempotencyKey_FullMethodName = "/payment.PaymentService/GetPaymentUrlByIdempotencyKey"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error)
	ConfirmPaymentIntent(ctx context.Context, in *ConfirmPaymentIntentRequest, opts ...grpc.CallOption) (*ConfirmPaymentIntentResponse, error)
	CancelPaymentIntent(ctx context.Context, in *CancelPaymentIntentRequest, opts ...grpc.CallOption) (*CancelPaymentIntentResponse, error)
	GetPaymentUrlByIdempotencyKey(ctx context.Context, in *GetPaymentUrlByIdempotencyKeyRequest, opts ...grpc.CallOption) (*GetPaymentUrlByIdempotencyKeyResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreatePaymentIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ConfirmPaymentIntent(ctx context.Context, in *ConfirmPaymentIntentRequest, opts ...grpc.CallOption) (*ConfirmPaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentService_ConfirmPaymentIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelPaymentIntent(ctx context.Context, in *CancelPaymentIntentRequest, opts ...grpc.CallOption) (*CancelPaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentService_CancelPaymentIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentUrlByIdempotencyKey(ctx context.Context, in *GetPaymentUrlByIdempotencyKeyRequest, opts ...grpc.CallOption) (*GetPaymentUrlByIdempotencyKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentUrlByIdempotencyKeyResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPaymentUrlByIdempotencyKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error)
	ConfirmPaymentIntent(context.Context, *ConfirmPaymentIntentRequest) (*ConfirmPaymentIntentResponse, error)
	CancelPaymentIntent(context.Context, *CancelPaymentIntentRequest) (*CancelPaymentIntentResponse, error)
	GetPaymentUrlByIdempotencyKey(context.Context, *GetPaymentUrlByIdempotencyKeyRequest) (*GetPaymentUrlByIdempotencyKeyResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaymentIntent not implemented")
}
func (UnimplementedPaymentServiceServer) ConfirmPaymentIntent(context.Context, *ConfirmPaymentIntentRequest) (*ConfirmPaymentIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPaymentIntent not implemented")
}
func (UnimplementedPaymentServiceServer) CancelPaymentIntent(context.Context, *CancelPaymentIntentRequest) (*CancelPaymentIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPaymentIntent not implemented")
}
func (UnimplementedPaymentServiceServer) GetPaymentUrlByIdempotencyKey(context.Context, *GetPaymentUrlByIdempotencyKeyRequest) (*GetPaymentUrlByIdempotencyKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentUrlByIdempotencyKey not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreatePaymentIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePaymentIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreatePaymentIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePaymentIntent(ctx, req.(*CreatePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ConfirmPaymentIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ConfirmPaymentIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ConfirmPaymentIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ConfirmPaymentIntent(ctx, req.(*ConfirmPaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelPaymentIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelPaymentIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CancelPaymentIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelPaymentIntent(ctx, req.(*CancelPaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentUrlByIdempotencyKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentUrlByIdempotencyKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentUrlByIdempotencyKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPaymentUrlByIdempotencyKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentUrlByIdempotencyKey(ctx, req.(*GetPaymentUrlByIdempotencyKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePaymentIntent",
			Handler:    _PaymentService_CreatePaymentIntent_Handler,
		},
		{
			MethodName: "ConfirmPaymentIntent",
			Handler:    _PaymentService_ConfirmPaymentIntent_Handler,
		},
		{
			MethodName: "CancelPaymentIntent",
			Handler:    _PaymentService_CancelPaymentIntent_Handler,
		},
		{
			MethodName: "GetPaymentUrlByIdempotencyKey",
			Handler:    _PaymentService_GetPaymentUrlByIdempotencyKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
