// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentProvider int32

const (
	PaymentProvider_UNKNOWN PaymentProvider = 0
	PaymentProvider_ZALOPAY PaymentProvider = 1
	PaymentProvider_PAYOS   PaymentProvider = 2
	PaymentProvider_VNPAY   PaymentProvider = 3
)

// Enum value maps for PaymentProvider.
var (
	PaymentProvider_name = map[int32]string{
		0: "UNKNOWN",
		1: "ZALOPAY",
		2: "PAYOS",
		3: "VNPAY",
	}
	PaymentProvider_value = map[string]int32{
		"UNKNOWN": 0,
		"ZALOPAY": 1,
		"PAYOS":   2,
		"VNPAY":   3,
	}
)

func (x PaymentProvider) Enum() *PaymentProvider {
	p := new(PaymentProvider)
	*p = x
	return p
}

func (x PaymentProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentProvider) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentProvider.Descriptor instead.
func (PaymentProvider) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_PENDING   PaymentStatus = 0
	PaymentStatus_COMPLETED PaymentStatus = 1
	PaymentStatus_FAILED    PaymentStatus = 2
	PaymentStatus_CANCELED  PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PENDING",
		1: "COMPLETED",
		2: "FAILED",
		3: "CANCELED",
	}
	PaymentStatus_value = map[string]int32{
		"PENDING":   0,
		"COMPLETED": 1,
		"FAILED":    2,
		"CANCELED":  3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

type CreatePaymentIntentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderCode      string                 `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	AmountCents    int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Provider       PaymentProvider        `protobuf:"varint,4,opt,name=provider,proto3,enum=payment.PaymentProvider" json:"provider,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RedirectUrl    string                 `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CreatePaymentIntentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetProvider() PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return PaymentProvider_UNKNOWN
}

func (x *CreatePaymentIntentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CreatePaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type ConfirmPaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentIntentRequest) Reset() {
	*x = ConfirmPaymentIntentRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentIntentRequest) ProtoMessage() {}

func (x *ConfirmPaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmPaymentIntentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type ConfirmPaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentIntentResponse) Reset() {
	*x = ConfirmPaymentIntentResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentIntentResponse) ProtoMessage() {}

func (x *ConfirmPaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmPaymentIntentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConfirmPaymentIntentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

type CancelPaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentIntentRequest) Reset() {
	*x = CancelPaymentIntentRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentIntentRequest) ProtoMessage() {}

func (x *CancelPaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CancelPaymentIntentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type CancelPaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentIntentResponse) Reset() {
	*x = CancelPaymentIntentResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentIntentResponse) ProtoMessage() {}

func (x *CancelPaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *CancelPaymentIntentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CancelPaymentIntentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

type GetPaymentUrlByIdempotencyKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentUrlByIdempotencyKeyRequest) Reset() {
	*x = GetPaymentUrlByIdempotencyKeyRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentUrlByIdempotencyKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentUrlByIdempotencyKeyRequest) ProtoMessage() {}

func (x *GetPaymentUrlByIdempotencyKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentUrlByIdempotencyKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentUrlByIdempotencyKeyRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentUrlByIdempotencyKeyRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetPaymentUrlByIdempotencyKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl    string                 `protobuf:"bytes,1,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentUrlByIdempotencyKeyResponse) Reset() {
	*x = GetPaymentUrlByIdempotencyKeyResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentUrlByIdempotencyKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentUrlByIdempotencyKeyResponse) ProtoMessage() {}

func (x *GetPaymentUrlByIdempotencyKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentUrlByIdempotencyKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentUrlByIdempotencyKeyResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentUrlByIdempotencyKeyResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *GetPaymentUrlByIdempotencyKeyResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PENDING
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"\xa5\x02\n" +
	"\x1aCreatePaymentIntentRequest\x12\x1d\n" +
	"\n" +
	"order_code\x18\x01 \x01(\tR\torderCode\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x124\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x18.payment.PaymentProviderR\bprovider\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\fredirect_url\x18\x06 \x01(\tR\vredirectUrl\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\">\n" +
	"\x1bCreatePaymentIntentResponse\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\"<\n" +
	"\x1bConfirmPaymentIntentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"m\n" +
	"\x1cConfirmPaymentIntentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\";\n" +
	"\x1aCancelPaymentIntentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"l\n" +
	"\x1bCancelPaymentIntentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\"O\n" +
	"$GetPaymentUrlByIdempotencyKeyRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"x\n" +
	"%GetPaymentUrlByIdempotencyKeyResponse\x12\x1f\n" +
	"\vpayment_url\x18\x01 \x01(\tR\n" +
	"paymentUrl\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.payment.PaymentStatusR\x06status*A\n" +
	"\x0fPaymentProvider\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aZALOPAY\x10\x01\x12\t\n" +
	"\x05PAYOS\x10\x02\x12\t\n" +
	"\x05VNPAY\x10\x03*E\n" +
	"\rPaymentStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\f\n" +
	"\bCANCELED\x10\x032\xb9\x03\n" +
	"\x0ePaymentService\x12`\n" +
	"\x13CreatePaymentIntent\x12#.payment.CreatePaymentIntentRequest\x1a$.payment.CreatePaymentIntentResponse\x12c\n" +
	"\x14ConfirmPaymentIntent\x12$.payment.ConfirmPaymentIntentRequest\x1a%.payment.ConfirmPaymentIntentResponse\x12`\n" +
	"\x13CancelPaymentIntent\x12#.payment.CancelPaymentIntentRequest\x1a$.payment.CancelPaymentIntentResponse\x12~\n" +
	"\x1dGetPaymentUrlByIdempotencyKey\x12-.payment.GetPaymentUrlByIdempotencyKeyRequest\x1a..payment.GetPaymentUrlByIdempotencyKeyResponseB9Z7github.com/vogiaan1904/ticketbottle-proto/proto/paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_proto_goTypes = []any{
	(PaymentProvider)(0),                          // 0: payment.PaymentProvider
	(PaymentStatus)(0),                            // 1: payment.PaymentStatus
	(*CreatePaymentIntentRequest)(nil),            // 2: payment.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil),           // 3: payment.CreatePaymentIntentResponse
	(*ConfirmPaymentIntentRequest)(nil),           // 4: payment.ConfirmPaymentIntentRequest
	(*ConfirmPaymentIntentResponse)(nil),          // 5: payment.ConfirmPaymentIntentResponse
	(*CancelPaymentIntentRequest)(nil),            // 6: payment.CancelPaymentIntentRequest
	(*CancelPaymentIntentResponse)(nil),           // 7: payment.CancelPaymentIntentResponse
	(*GetPaymentUrlByIdempotencyKeyRequest)(nil),  // 8: payment.GetPaymentUrlByIdempotencyKeyRequest
	(*GetPaymentUrlByIdempotencyKeyResponse)(nil), // 9: payment.GetPaymentUrlByIdempotencyKeyResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.CreatePaymentIntentRequest.provider:type_name -> payment.PaymentProvider
	1, // 1: payment.ConfirmPaymentIntentResponse.status:type_name -> payment.PaymentStatus
	1, // 2: payment.CancelPaymentIntentResponse.status:type_name -> payment.PaymentStatus
	1, // 3: payment.GetPaymentUrlByIdempotencyKeyResponse.status:type_name -> payment.PaymentStatus
	2, // 4: payment.PaymentService.CreatePaymentIntent:input_type -> payment.CreatePaymentIntentRequest
	4, // 5: payment.PaymentService.ConfirmPaymentIntent:input_type -> payment.ConfirmPaymentIntentRequest
	6, // 6: payment.PaymentService.CancelPaymentIntent:input_type -> payment.CancelPaymentIntentRequest
	8, // 7: payment.PaymentService.GetPaymentUrlByIdempotencyKey:input_type -> payment.GetPaymentUrlByIdempotencyKeyRequest
	3, // 8: payment.PaymentService.CreatePaymentIntent:output_type -> payment.CreatePaymentIntentResponse
	5, // 9: payment.PaymentService.ConfirmPaymentIntent:output_type -> payment.ConfirmPaymentIntentResponse
	7, // 10: payment.PaymentService.CancelPaymentIntent:output_type -> payment.CancelPaymentIntentResponse
	9, // 11: payment.PaymentService.GetPaymentUrlByIdempotencyKey:output_type -> payment.GetPaymentUrlByIdempotencyKeyResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
